version: "3.8"

services:
  node_backend:
    container_name: node-studentResult
    image: nodeStudentResult
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ydcpupijjulbdw
      - POSTGRES_PASSWORD=1bf091527567094ec723bc3b77fefe49542fa6109bc87ad1dd749ad066231edf
      - POSTGRES_DB=d1c0o68hiac5g8
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
